runtime: python
env: flex

runtime_config:
  python_version: 3
  entrypoint: ./start.sh

service: default

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

readiness_check:
  app_start_timeout_sec: 300

handlers:
  - url: /.*
    script: main.py  # Automatically route requests to your main Python script (e.g., main.py)

env_variables:
  # Define any environment variables your application needs
  ENV_VAR_NAME: "value"
  # Add more environment variables as needed

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cpu_utilization:
    target_utilization: 0.5